export const ALLOWED_AUDIO_TYPES = [
  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
  "audio/x-wav",
  "audio/wave",
  "audio/mp4",
  "audio/x-m4a",
  "audio/ogg",
  "audio/flac",
  "audio/x-flac",
  "audio/aac",
  "audio/x-aac",
  "audio/wma",
  "audio/x-ms-wma",
  "audio/opus",
  "audio/x-opus",
  "audio/aiff",
  "audio/x-aiff",
  "audio/webm",
] as const;
