/**
 * Customer-facing product language.
 * Prefer these over internal terms (stream / takehome / budget).
 */

export const UX = {
  /** Per-voice play control: short stock demo, not the uploaded book. */
  preview: "Preview",
  tryChapter: "Listening",
  tryChapterShort: "Listening",
  wholeBook: "Get the whole book",
  wholeBookShort: "Whole book",
  /** Voice-step primary: Trigger take-home job. */
  makeAudiobook: "Make audiobook",
  /** Per-voice choose-this-narrator affordance on the card. */
  useVoice: "Use",
  /** Quiet non-blocking extract status on the voice step. */
  preparingText: "Preparing text…",

  startListening: "Listening",
  /** Short narrator sample (not the book). */
  liveListen: "Preview",
  liveListenStop: "Stop",
  saveFullBook: "Save full audiobook",
  fullBookStarted: "Generating your full audiobook…",
  startingChapter: "Opening…",

  listening: "Listening",
  savedBook: "Full audiobook",
  ready: "Ready",
  generating: "Generating",
  starting: "Starting",
  failed: "Failed",
  cancelled: "Cancelled",
  readyToPlay: "Ready to play",

  listeningTimeUsed: "Listening time used",
  listeningLimitReached:
    "Listening limit reached. Save the full audiobook to keep going.",
  listeningPaused:
    "Listening paused. Save the full audiobook to keep the whole book.",
  continuing: "Continuing…",
  preparingAudio: "Preparing audio…",
  openingBook: "Opening your book…",
  preparingNarrator: "Preparing narrator…",
  almostReady: "Almost ready…",
  stillWarming:
    "Still warming up — try again in a moment if this takes too long.",
  seekingUnavailable: "Seeking unavailable",

  previewHint: "A short clip of how this narrator sounds — not your book.",
  tryChapterBlurb:
    "Play a short sample of the voice. It is not your book.",
  wholeBookBlurb:
    "Generate a downloadable audiobook with your narrator.",
  narrationDelivery: "Narration delivery",
  narrationDeliveryHint:
    "Auto matches this book. Override if you want sparser pauses or plainer titles.",
  pauseStyle: "Pauses",
  pauseAuto: "Auto",
  pauseSparse: "Sparse",
  pauseNormal: "Normal",
  joinStyle: "Joins",
  joinAuto: "Auto",
  joinShort: "80ms",
  joinSoft: "120ms",
  joinLong: "150ms",
  titleCleanup: "Titles",
  titleAuto: "Auto",
  titleClean: "Clean",
  titleKeep: "Keep",
  toneStyle: "Tone",
  toneAuto: "Auto",
  toneSeminar: "Seminar",
  tonePlain: "Plain",

  recentlyHeard: "Recently heard",
  compare: "Compare",
  howItWorks: "How it works",
  cloneSampleTip:
    "Good clones need a dry room and a phone close to your mouth. Cleaning tools won't rescue echo.",
} as const;

/** Voice-step fork. Standard is the stock path — never “Classic”. */
export const VOICE_PATH = {
  standardTitle: "Standard",
  cloneTitle: "Clone",
  backToPaths: "Paths",
  noClones: "No clones yet.",
  cloneUnavailable: "Voice cloning isn’t available right now.",
} as const;

/** Landing + chrome verbs. Keep these dry — no immersion copy. */
export const LANDING = {
  createCta: "Create audiobook",
  libraryCta: "Library",
  signInCta: "Sign in",
  signOutCta: "Sign out",
  uploadTab: "Upload",
  pasteTab: "Paste",
  howItWorks: "How it works",
} as const;

/** Signed-in account menu. Provider names stay out of the trigger label. */
export const NAV = {
  account: "Account",
  settings: "Settings",
  library: "Library",
  darkMode: "Dark mode",
  signOut: "Sign out",
} as const;

/** Public /privacy facts for Google OAuth consent. Do not invent extras. */
export const PRIVACY = {
  title: "Privacy",
  site: "Echomancer (https://echomancer.xyz) turns uploaded books and pasted text into audiobooks.",
  uploads:
    "We store uploaded books and pasted text only to generate your audiobook. You can delete them from your library.",
  clones:
    "If you clone a voice, we store the audio sample so we can create and use that clone.",
  auth: "You can use the site with a signed anonymous cookie. Google sign-in stores your name, email, and profile image so we can keep your library.",
  storage:
    "Audio and documents are stored on Cloudflare R2. Job metadata is stored in Turso. Speech is generated by our text-to-speech provider.",
  selling: "We do not sell personal data.",
  contact: "Questions: ntemusejoel@gmail.com",
} as const;

export type LibraryStatus =
  | "ready"
  | "generating"
  | "starting"
  | "failed"
  | "cancelled"
  | "ready_to_play"
  | "listening";

export function libraryStatus(job: {
  status: string;
  job_kind?: string | null;
  segments?: Array<{ status: string }> | null;
}): { id: LibraryStatus; label: string } {
  // `cancelled` is deliberately distinct from `failed`: nothing went wrong, so
  // offering "Retry" for it would misread the user's intent.
  if (job.status === "cancelled") {
    return { id: "cancelled", label: UX.cancelled };
  }
  if (job.status === "failed") return { id: "failed", label: UX.failed };
  if (job.status === "ready") return { id: "ready", label: UX.ready };
  if (job.job_kind === "stream") {
    return { id: "listening", label: UX.listening };
  }
  if (
    (job.status === "processing" || job.status === "queued") &&
    job.segments?.some((s) => s.status === "ready")
  ) {
    return { id: "ready_to_play", label: UX.readyToPlay };
  }
  if (job.status === "queued") return { id: "starting", label: UX.starting };
  if (job.status === "processing") {
    return { id: "generating", label: UX.generating };
  }
  return { id: "generating", label: UX.generating };
}

export function kindLabel(jobKind?: string | null): string | null {
  if (jobKind === "takehome") return UX.savedBook;
  return null;
}
