import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { libraryStatus, kindLabel, LANDING, PRIVACY, UX } from "./ux-copy";

const MARKETING_FLUFF = [
  "A space for immersion",
  "immersion",
  "transcend the page",
  "Books expand minds",
  "Voice carries meaning",
];

function sourceOf(relPath: string): string {
  return readFileSync(resolve(process.cwd(), relPath), "utf8");
}

function assertNoFluff(text: string, label: string) {
  for (const phrase of MARKETING_FLUFF) {
    expect(text, `${label} must not include “${phrase}”`).not.toMatch(
      new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i")
    );
  }
}

describe("ux-copy", () => {
  it("maps jobs to library mental-model statuses", () => {
    expect(libraryStatus({ status: "ready" }).label).toBe(UX.ready);
    expect(libraryStatus({ status: "failed" }).label).toBe(UX.failed);
    expect(libraryStatus({ status: "queued" }).label).toBe(UX.starting);
    expect(
      libraryStatus({
        status: "processing",
        segments: [{ status: "ready" }],
      }).label
    ).toBe(UX.readyToPlay);
    expect(
      libraryStatus({ status: "ready", job_kind: "stream" }).label
    ).toBe(UX.ready);
    expect(
      libraryStatus({ status: "queued", job_kind: "stream" }).label
    ).toBe(UX.listening);
  });

  it("labels job kinds for customers", () => {
    expect(kindLabel("stream")).toBe(UX.tryChapter);
    expect(kindLabel("takehome")).toBe(UX.savedBook);
  });

  it("keeps landing copy short and practical", () => {
    expect(LANDING.heroSubtitle.toLowerCase()).toMatch(/upload|paste/);
    expect(LANDING.heroSubtitle.toLowerCase()).toMatch(/audiobook/);
    expect(LANDING.heroSubtitle).not.toMatch(/fish/i);
    expect(LANDING.heroSubtitle.length).toBeLessThan(140);
    expect(LANDING.createCta).toBe("Create audiobook");
    expect(LANDING.libraryCta).toBe("Library");
    expect(LANDING.signInCta).toBe("Sign in with Google");
    expect(LANDING.features).toHaveLength(3);
    expect(LANDING.features.map((f) => f.label)).not.toContain("Fish Audio");
    for (const feature of LANDING.features) {
      expect(feature.label).not.toMatch(/fish/i);
      expect(feature.label.split(" ").length).toBeLessThanOrEqual(3);
      expect(feature.detail.length).toBeLessThan(80);
      expect(feature.detail).not.toMatch(/fish/i);
    }
    expect(UX.wholeBookBlurb).not.toMatch(/fish/i);
    assertNoFluff(
      [
        LANDING.heroSubtitle,
        LANDING.createCta,
        ...LANDING.features.flatMap((f) => [f.label, f.detail]),
        LANDING.privacy,
      ].join("\n"),
      "LANDING"
    );
  });

  it("drops immersion fluff from landing and chrome surfaces", () => {
    const surfaces = [
      "src/components/landing-page.tsx",
      "src/components/auth-controls.tsx",
      "src/app/dashboard/chrome.tsx",
      "src/app/dashboard/voice/page.tsx",
      "src/app/dashboard/queue/page.tsx",
      "src/app/dashboard/resources/page.tsx",
    ];
    for (const file of surfaces) {
      assertNoFluff(sourceOf(file), file);
    }
    expect(sourceOf("src/components/landing-page.tsx")).not.toMatch(/drawably/i);
    expect(sourceOf("package.json")).not.toMatch(/drawably/);
    expect(sourceOf("src/app/dashboard/resources/page.tsx")).not.toMatch(
      /feels clear/i
    );
  });

  it("states only real privacy facts for OAuth consent", () => {
    const text = [
      PRIVACY.site,
      PRIVACY.uploads,
      PRIVACY.clones,
      PRIVACY.auth,
      PRIVACY.storage,
      PRIVACY.selling,
      PRIVACY.contact,
    ].join("\n");
    expect(text).toMatch(/echomancer\.xyz/i);
    expect(text).toMatch(/uploaded books|pasted text/i);
    expect(text).toMatch(/delete/i);
    expect(text).toMatch(/clone/i);
    expect(text).toMatch(/Google/i);
    expect(text).toMatch(/name/i);
    expect(text).toMatch(/email/i);
    expect(text).toMatch(/anonymous|signed cookie/i);
    expect(text).toMatch(/Cloudflare R2/i);
    expect(text).toMatch(/Turso/i);
    expect(text).toMatch(/speech is generated by our text-to-speech provider/i);
    expect(text).not.toMatch(/fish/i);
    expect(text).toMatch(/do not sell/i);
    expect(text).toContain("ntemusejoel@gmail.com");
    assertNoFluff(text, "PRIVACY");
  });

  it("keeps Fish vendor names out of customer-facing copy", () => {
    const vendor = /Fish Audio|\bFish narrator\b|powered by Fish|Fish Audio API/i;
    const surfaces = [
      "src/lib/ux-copy.ts",
      "src/app/layout.tsx",
      "src/app/privacy/page.tsx",
      "src/components/landing-page.tsx",
      "src/components/auth-controls.tsx",
      "src/app/dashboard/chrome.tsx",
      "src/app/dashboard/voice/page.tsx",
      "src/app/dashboard/queue/page.tsx",
      "src/app/dashboard/resources/page.tsx",
      "src/app/dashboard/player/[id]/page.tsx",
    ];
    for (const file of surfaces) {
      expect(sourceOf(file), file).not.toMatch(vendor);
    }
    expect(sourceOf("src/app/layout.tsx")).not.toMatch(/Fish Audio turns/i);
    expect(sourceOf("src/app/dashboard/voice/page.tsx")).not.toMatch(
      /No Fish narrators/i
    );
    expect(sourceOf("src/app/dashboard/resources/page.tsx")).not.toMatch(
      /Fish Audio only/i
    );
  });

  it("publishes /privacy and links it from the landing footer", () => {
    const page = sourceOf("src/app/privacy/page.tsx");
    expect(page).toContain("PRIVACY");
    expect(sourceOf("src/components/landing-page.tsx")).toMatch(
      /href=["']\/privacy["']/
    );
    assertNoFluff(page, "src/app/privacy/page.tsx");
  });
});
