/**
 * Customer-facing product language.
 * Prefer these over internal terms (stream / takehome / budget).
 */

export const UX = {
  /** Primary mode: stream the book live via Fish. */
  tryChapter: "Live Stream",
  tryChapterShort: "Live Stream",
  wholeBook: "Get the whole book",
  wholeBookShort: "Whole book",

  /** Start the book live-stream job. */
  startListening: "Live Stream",
  /** Short Fish sample (not the book). */
  liveListen: "Live Listen",
  liveListenStop: "Stop",
  saveFullBook: "Save full audiobook",
  fullBookStarted: "Generating your full audiobook…",
  startingChapter: "Opening live stream…",

  listening: "Live Stream",
  savedBook: "Full audiobook",
  ready: "Ready",
  generating: "Generating",
  starting: "Starting",
  failed: "Failed",
  cancelled: "Cancelled",
  readyToPlay: "Ready to play",

  listeningTimeUsed: "Listening time used",
  listeningLimitReached:
    "Listening limit reached. Save the full audiobook to keep going.",
  listeningPaused:
    "Listening paused. Save the full audiobook to keep the whole book.",
  continuing: "Continuing…",
  preparingAudio: "Preparing audio…",
  openingBook: "Opening your book…",
  preparingNarrator: "Preparing narrator…",
  almostReady: "Almost ready…",
  stillWarming:
    "Still warming up — try again in a moment if this takes too long.",
  seekingUnavailable: "Live stream · seeking unavailable",

  previewHint:
    "Live Listen is a short sample. Live Stream opens the book.",
  tryChapterBlurb:
    "Stream the book as audio generates. About an hour of listening.",
  wholeBookBlurb:
    "Generate a downloadable audiobook with your narrator.",

  recentlyHeard: "Recently heard",
  compare: "Compare",
  resourcesSubtitle: "Formats, voices, and how generation works.",
  librarySubtitle: "Your audiobooks.",
  cloneSampleTip:
    "Good clones need a dry room and a phone close to your mouth. Cleaning tools won't rescue echo.",
} as const;

/** Landing + chrome verbs. Keep these dry — no immersion copy. */
export const LANDING = {
  heroSubtitle:
    "Upload a book or paste text. Turn it into an audiobook.",
  createCta: "Create audiobook",
  libraryCta: "Library",
  signInCta: "Sign in with Google",
  signOutCta: "Sign out",
  uploadTab: "Upload",
  pasteTab: "Paste",
  features: [
    {
      label: "Narrator",
      detail: "Stock Narrator, or a clone from a short sample.",
    },
    {
      label: "Live Stream",
      detail: "Listen while it generates. About an hour.",
    },
    {
      label: "Whole book",
      detail: "Full downloadable file when you want it.",
    },
  ],
  privacy:
    "Uploaded books and pasted text are stored only to generate your audiobook, and are removed when you delete it from your library.",
} as const;

/** Public /privacy facts for Google OAuth consent. Do not invent extras. */
export const PRIVACY = {
  title: "Privacy",
  site: "Echomancer (https://echomancer.xyz) turns uploaded books and pasted text into audiobooks.",
  uploads:
    "We store uploaded books and pasted text only to generate your audiobook. You can delete them from your library.",
  clones:
    "If you clone a voice, we store the audio sample so we can create and use that clone.",
  auth: "You can use the site with a signed anonymous cookie. Google sign-in stores your name, email, and profile image so we can keep your library.",
  storage:
    "Audio and documents are stored on Cloudflare R2. Job metadata is stored in Turso. Speech is generated by our text-to-speech provider.",
  selling: "We do not sell personal data.",
  contact: "Questions: ntemusejoel@gmail.com",
} as const;

export type LibraryStatus =
  | "ready"
  | "generating"
  | "starting"
  | "failed"
  | "cancelled"
  | "ready_to_play"
  | "listening";

export function libraryStatus(job: {
  status: string;
  job_kind?: string | null;
  segments?: Array<{ status: string }> | null;
}): { id: LibraryStatus; label: string } {
  // `cancelled` is deliberately distinct from `failed`: nothing went wrong, so
  // offering "Retry" for it would misread the user's intent.
  if (job.status === "cancelled") {
    return { id: "cancelled", label: UX.cancelled };
  }
  if (job.status === "failed") return { id: "failed", label: UX.failed };
  if (job.status === "ready") return { id: "ready", label: UX.ready };
  if (job.job_kind === "stream") {
    return { id: "listening", label: UX.listening };
  }
  if (
    (job.status === "processing" || job.status === "queued") &&
    job.segments?.some((s) => s.status === "ready")
  ) {
    return { id: "ready_to_play", label: UX.readyToPlay };
  }
  if (job.status === "queued") return { id: "starting", label: UX.starting };
  if (job.status === "processing") {
    return { id: "generating", label: UX.generating };
  }
  return { id: "generating", label: UX.generating };
}

export function kindLabel(jobKind?: string | null): string | null {
  if (jobKind === "stream") return UX.tryChapter;
  if (jobKind === "takehome") return UX.savedBook;
  return null;
}
